[tier]
COMMON = "âšª"
RARE = "ğŸ”µ"
EPIC = "ğŸŸ£"
LEGENDARY = "ğŸŸ "
MYTHICAL = "ğŸŸ¤"
DIVINE = "âšª"
PERK = "ğŸŸ¡"

[element]
PHYSICAL = "<:phydmg:725871208830074929>"
EXPLOSIVE = "<:expdmg:725871223338172448>"
ELECTRIC = "<:eledmg:725871233614479443>"
COMBINED = "<:combined:1026853188940349490>"
UNKNOWN = "â”"

[type]
TORSO = "<:torso:730115680363347968>"
LEGS = "<:legs:730115699397361827>"
DRONE = "<:drone:730115574763618394>"
SIDE_WEAPON_R = "<:sider:730115747799629940>"
SIDE_WEAPON_L = "<:sidel:730115729365663884>"
TOP_WEAPON_R = "<:topr:730115786735091762>"
TOP_WEAPON_L = "<:topl:730115768431280238>"
TELEPORTER = "<:tele:730115603683213423>"
CHARGE = "<:charge:730115557239685281>"
HOOK = "<:hook:730115622347735071>"
MODULE = "<:mod:730115649866694686>"

[stats]
weight = "<:weight:725870760484143174>"
health = "<:health:725870887588462652>"
eneCap = "<:energy:725870941883859054>"
eneReg = "<:regen:725871003665825822>"
heaCap = "<:heat:725871043767435336>"
heaCol = "<:cooling:725871075778363422>"
bulletsCap = "ğŸ§°"
rocketsCap = "ğŸ§°"
phyRes = "<:phyres:725871121051811931>"
expRes = "<:expres:725871136935772294>"
eleRes = "<:elecres:725871146716758077>"
phyDmg = "<:phydmg:725871208830074929>"
phyResDmg = "<:phyresdmg:725871259635679263>"
expDmg = "<:expdmg:725871223338172448>"
heaDmg = "<:headmg:725871613639393290>"
heaCapDmg = "<:heatcapdmg:725871478083551272>"
heaColDmg = "<:coolingdmg:725871499281563728>"
expResDmg = "<:expresdmg:725871281311842314>"
eleDmg = "<:eledmg:725871233614479443>"
eneDmg = "<:enedmg:725871599517171719>"
eneCapDmg = "<:enecapdmg:725871420126789642>"
eneRegDmg = "<:regendmg:725871443815956510>"
eleResDmg = "<:eleresdmg:725871296381976629>"
range = "<:range:725871752072134736>"
push = "<:push:725871716613488843>"
pull = "<:pull:725871734141616219>"
recoil = "<:recoil:725871778282340384>"
retreat = "<:retreat:725871804236955668>"
advance = "<:advance:725871818115907715>"
walk = "<:walk:725871844581834774>"
jump = "<:jump:725871869793796116>"
uses = "<:uses:725871917923303688>"
backfire = "<:backfire:725871901062201404>"
heaCost = "<:heatgen:725871674007879740>"
eneCost = "<:eneusage:725871660237979759>"
bulletsCost = "ğŸ¥•"
rocketsCost = "ğŸš€"